//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_mini.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Mechanic = new HashSet<Mechanic>();
        }
    
        public int ID { get; set; }
        public string AreaName { get; set; }
        public byte IsActive { get; set; }
    
        public virtual ICollection<Mechanic> Mechanic { get; set; }
    }
}
