//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_mini.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mechanic
    {
        public int ID { get; set; }
        public int AreaID { get; set; }
        public string MechanicName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public byte IsActive { get; set; }
    
        public virtual Area Area { get; set; }
    }
}
